note left of Drink: Component
abstract class Drink {
    + float cost()
}
note left of Coffee: Component 和 ConcreteComponent 之間緩衝
class Coffee extends Drink {

}
note bottom of ShortBlack: coffee 單品
class ShortBlack extends Coffee {

}

class LongBlack extends Coffee {
    
}

class Espresso extends Coffee {
    
}
note left of Decorator: 裝飾類，drink 被裝飾者
class Decorator extends Drink{
    - Drink drink()
}


class Chocolate extends Decorator {

}

class Milk extends Decorator {
    
}

class Soy extends Decorator {
    
}