interface Subject {
    + registerObserver(o: Observer): void
    + remove(o: Observer): void
    + notifyObservers(): void
}

class WeatherData implements Subject {
    - observers: ArrayList
}

note left of WeatherData: 核心類，1. 天氣訊息 2. 管理觀察者 Observers

interface Observer {
    + update(): void
}

Subject ..> Observer
Observer ..o WeatherData

class Google implements  Observer {

}

class Yahoo implements  Observer {
    
}

class Client {

}

Client ..> Subject
Client ..> Observer