note left of AbstractClass: template 定義了 operation 的執行，operation 可以為抽象或是實現方法
abstract class AbstractClass {
    + void template()
    + void operation1()
    + void operation2()
    + void operation3()
}
note left of ConceteClass: 其定義的 operation1 與 ConceteClassB 不同
class ConceteClass extends AbstractClass {
    + void operation1()
    + void operation2()
    + void operation3()
}

class ConceteClassB extends AbstractClass {
    + void operation1()
    + void operation2()
    + void operation3()
}

class Client {

}

Client ..> ConceteClass
Client ..> ConceteClassB