abstract class Mediator {

}

note right of ConcreteMediator: 1. 管理所有 Colleague 具體類 2. 完成相對應動作和任務

class ConcreteMediator extends Mediator {
    - colleagues: HashMap
}

abstract class Colleague {

}
note left of ConcreteColleague: 使用建構方法獲取 Mediator
class ConcreteColleague extends Colleague {
    ConcreteColleague()
}


Mediator --- Colleague

Colleague --o ConcreteMediator

ConcreteColleague ..> Mediator

class Client {

}


Client ..> Mediator
Client ..> Colleague