note top of Voltage220 : 被適配
class Voltage220 {
    + void output220V()
}
note top of Voltage5V : 適配接口
interface Voltage5V {
    + void output5V()
}
note top of VoltageAdapter : 適配器類
class VoltageAdapter extends Voltage220 implements Voltage5V {

}

class Phone {
    + void charging()
}

class Client {

}

Phone ..> Voltage5V
Client ..> Phone
Client ..> VoltageAdapter