' 命令角色，需要執行的所有命令，為抽象或接口類
interface Command {
    + void execute()
    + void undo()
}
' 將一個接收者物件與一個動作綁定，調用接收者相應操作，實現 execute
class ConcreteCommand extends Command{
    + void execute()
    + void undo()
}
' 接收者角色，知道如何實施和執行一個請求相關操作
class Receiver {

}
' 調用者角色
class Invoker {

}


class Client {

}


ConcreteCommand o-- Receiver
Invoker o-- Command
Client ..> Invoker
Client ..> Receiver
Client ..> ConcreteCommand