class Flyweight {
    + Operation()
}

class FlyweightFactory {
    + GetFlyweight(Key)
}

class ConcreteFlyweight extends FlyweightFactory {

}

class UnsharedConcreteFlyweight extends FlyweightFactory {

}

class Client {

}

FlyweightFactory "+flyweights" o--> Flyweight

Client --> FlyweightFactory
Client --> ConcreteFlyweight
Client --> UnsharedConcreteFlyweight