interface Brand {
    + void call()
}

class Vivo implements Brand {

}

class XiaoMi implements Brand {

}

abstract Phone {
    - Brand brand
}

class FoldedPhone extends Phone {

}

class UpRightPhone extends Phone {

}

class Client {

}

Phone o-- Brand

Client ..> Phone
Client ..> Brand