class TeacherDAO implements ITeacherDAO {
    + void teach()
}

interface ITeacherDAO {
    + void teach()
}

class TeacherDAOProxy implements ITeacherDAO {
    + void teach()
}
' 1. 創建 TeacherDAOProxy 物件
' 2. 創建 TeacherDAO 物件
' 3. 將 TeacherDAO 物件，交給 TeacherDAOProxy 物件執行方法
class Client {

}

TeacherDAO --o TeacherDAOProxy
Client ..> TeacherDAOProxy
Client ..> TeacherDAO