interface IteacherDAO {
    + void teach()
}

class TeacherDAO implements IteacherDAO {
    + void teach()
}
' getProxyInstance
' 1. 根據傳入的物件(TeacherDAO)目標物件
' 2. 利用反射機制，返回一個代理物件
' 3. 然後透過代理物件，調用目標物件方法
class ProxyFactory {
    + ProxyFactory
    + Object getProxyInstance()
}

class Client {

}


Client ..> ProxyFactory
Client ..> TeacherDAO