' Flyweight
class WebSite {
    + void use()
}

' ConcreteFlyweight
class ConcreteWebSite extends WebSite {
    + void use()
}

' FlyweightFactory

class WebSiteFactory {
    + void getWebSiteCategory()
}
' 外部狀態
class User {

}

class Client {

}







WebSiteFactory o-- WebSite

Client ..> WebSiteFactory
Client ..> ConcreteWebSite

ConcreteWebSite ..> User
Client ..> User