note left of Voltage220 : 被適配
class Voltage220 {
    + void output220V()
}
note left of Voltage5V : 適配接口
interface Voltage5V {
    + void output5V()
}
note right of VoltageAdapter : 適配器類
class VoltageAdapter implements Voltage5V {
    - Voltage220 voltage220
    + VoltageAdapter(Voltage220 voltage220)
}

class Phone {
    + void charging(Voltage5V voltage5V)
}

class Client {

}

Phone ..> Voltage5V
VoltageAdapter o-- Voltage220
Client ..> Phone
Client ..> VoltageAdapter
Client ..> Voltage5V