class Memento {
    - state: String
}

class Caretaker {
    + mementos: ArrayList<>()
}

class Originator {

}

class Client {

}


Client ..> Memento
Client ..> Originator
Originator ..> Memento
Memento ..o Caretaker