note top of OrganizationComponent: 可以為具體類或是抽象與接口類
class OrganizationComponent {
    + void add()
    + void remove()
    + void print()
}
note left of University: Composite
class University extends OrganizationComponent {

}
note left of College: Composite
class College extends OrganizationComponent {

}
note left of Department: Leaf，最下面的部門
class Department extends OrganizationComponent {

}

class Client {

}

University o-- College 
College o--  Department

Client ..> OrganizationComponent