abstract Expression {
    + interpreter() : void
}

class VarExpression extends Expression {

}

class SymbolExpression extends Expression {
    
}

class SubExpression extends  SymbolExpression {

}

class AddExpression extends  SymbolExpression {
    
}

Expression --o SymbolExpression

class Calculator {
    
}

Expression --o Calculator

class Client {

}

Client ..> Calculator